### PR TITLE
Dump RC2 into RA2 for the next GSMA update

### PR DESCRIPTION
**Pull request by collivier**
This PR dumps the RC2 chapter02 and chapter03 into RA2 chapter07.
Please note that the former RA2 chapter07 is renamed chapter08 to fit the document logic.

This commits will be cherry-picked to stable/pieman asis to fit the GSMA processes.

### CODE REVIEW

**Comment by collivier** [comment]
@rgstori @CsatariGergely They remain "Requirements and Testing Principles" and "Test Case Integration and Tooling" which are part of NG133.

Do you prefer a duplicate (OpenStack would have to changed by Kubernetes of courses) or references to NG133.

**Comment by CsatariGergely** [comment]
I think the plan was to keep the RC2 project separately and modify the GSMA build process in a way that it picks the relevant RC2 chapters. 

For me this is also okay, however if we dump the content of RC2 to RA2 we should agree on how do we organize the work. Do we keep RC2 as a separate sub-project of Anuket or not.

**Comment by collivier** [comment]
@CsatariGergely Our target is to build the GSMA doc from our source code and not by extra processes which will fail in a long run and will mislead our endusers.

Let's follow NG133  as we agreed on this process during ONES. The relevant RC2 chapters should be moved to RA2 and then RC2 can be closed as for RC1.

**Review by rgstori — CHANGES_REQUESTED** [review]
for me it's ok, as long as @collivier keeps ownership of the RC2 project and content (please change the codeowners file), and if we merge chapters 6 and 7 (of the dump_rc2 branch) into a single chapter

**Comment by CsatariGergely** [comment]
Cool, I think we would still need to add the testing cookbook from [Chapter 03](https://github.com/anuket-project/RC2/blob/main/doc/ref_cert/RC2/chapters/chapter03.rst) and the traceability matrix from [Chapter 04](https://github.com/anuket-project/RC2/blob/main/doc/ref_cert/RC2/chapters/chapter04.rst#traceability-matrix)

**Comment by CsatariGergely** [comment]
"TSC agrees to move the content of RC2 to the RA2 repository with the condition that RC2 will be developed as a separate project from the RA2 project" from the TSC meeting of [13.08.2024](https://wiki.anuket.io/display/HOME/2024-08-13+TSC+Agenda+and+Minutes)

**Comment by rgstori** [comment]
@collivier can you please move the RC2 content (now ch7) in this branch into chapter 6, so that it's together with the API and Feature Testing requirements, just before the existing tables. you can rename it "Conformance testing" or something similar please?
thanks

**Comment by collivier** [comment]
@rgstori hi. Does it conform with your last proposal ?

**Review by CsatariGergely — CHANGES_REQUESTED** [review]
We should move the links to the refs.bib file. I can help to add part of them is needed.

**Comment by collivier** [comment]
@CsatariGergely  yes of couse but I would like us first to agree on form (document structure) and then I will finish the actions already identified. Is that what expected by RA2 team ?

**Review by rgstori — APPROVED** [review]
Thanks @collivier - the structure is ok now

**Comment by collivier** [comment]
@rgstori @CsatariGergely  it seems I cannot create issues here. Please note a few links are incorrect:

- (chapters/chapter01: line  614) redirect  https://www.alibabacloud.com/blog/what-can-we-learn-from-twitters-move-to-kubernetes_595156 - with Found to https://www.alibabacloud.com/notfound
- (chapters/chapter01: line  614) redirect  https://tungsten.io/ - permanently to https://lfnetworking.org

**Comment by CsatariGergely** [comment]
> @rgstori @CsatariGergely it seems I cannot create issues here. Please note a few links are incorrect:
> 
>     * (chapters/chapter01: line  614) redirect  https://www.alibabacloud.com/blog/what-can-we-learn-from-twitters-move-to-kubernetes_595156 - with Found to https://www.alibabacloud.com/notfound
> 
>     * (chapters/chapter01: line  614) redirect  https://tungsten.io/ - permanently to https://lfnetworking.org

@collivier yes, we manage the issues of the Anuket Specification sub projects in https://github.com/anuket-project/anuket-specifications/issues

The correct link for the Alibaba blog is https://www.alibabacloud.com/blog/twitter-announced-switch-from-mesos-to-kubernetes_595156. I think we should just remove Tungsten as it is not active anymore.

**Comment by collivier** [comment]
@rgstori @CsatariGergely it's ready for reviews.

Please note the follwing warning: doc/ref_arch/kubernetes/gsma/index.rst:1213: WARNING: duplicate label index:definitions, other instance in doc/ref_arch/kubernetes/gsma/index.rst

**Comment by collivier** [comment]
Please also note the intersphinx_mapping is incorrect as it should rather be cite to GSMA doc

intersphinx_mapping = {
     'cntt': ('https://cntt.readthedocs.io/en/latest/', None),
-    'ref_model': ('https://cntt.readthedocs.io/projects/rm/en/latest/', None),
     'ref_impl2': ('https://cntt.readthedocs.io/projects/ri2/en/latest/', None),
-    'ref_arch1': ('https://cntt.readthedocs.io/projects/ra1/en/latest/', None)
 }

**Comment by collivier** [comment]
@CsatariGergely  any news ?

**Comment by CsatariGergely** [comment]
Uh-oh, sorry. I've missed these. They are valid comments and need a fix. 

I've created a pr here: https://github.com/anuket-project/RA2/pull/26 if that is better from this pr-s point of view I can create the pr also against the [collivier:dump_rc2](https://github.com/collivier/RA2/tree/dump_rc2) branch.

**Comment by collivier** [comment]
@CsatariGergely I can rebase on top any change and you're allowed to edit this PR. The change doesn't conflict so they can be merged in any order.

I approved the other change.

**Comment by rgstori** [comment]
@cedric this looks ready now, can you rebase off the current main branch please?

**Review by petorre — APPROVED** [review]

**Pull request merged**
